# Example configuration file for EU-CLAMS
app_name: EU-CLAMS
database_path: ./data/db.yaml
player_name: YourCharacterName
team_name: YourTeamName
chat_log_path: C:\Users\YourUser\Documents\Entropia Universe\chat.log
enable_screenshots: true
screenshot_directory: ./data/screenshots
screenshot_delay: 0.6
game_window_title: Entropia Universe Client
enable_web_server: false
web_server_port: 8080
