[Details]
Website = "https://github.com/CloudNomster/EU-CLAMS"
Description = "Entropia Universe Chat Log Analyzer and Monitor"

[Release]
Icon = "Icon.png"

[App]
ID = "com.github.eu-clams"
Name = "EU-CLAMS"
Version = "0.1.4"
Build = 1
