name: PR Checks

on:
  merge_group:
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  test-and-build:
    name: Run Tests and Build
    runs-on: nomsterrunner  # Using the specified self-hosted Linux runner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'  # Using the same Go version as in go.mod
          cache: true

      - name: Install dependencies (system and Go packages)
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libgl1-mesa-dev xorg-dev gcc-mingw-w64-x86-64 gcc-mingw-w64
          go mod download

      - name: Run Tests
        run: go test -v ./...
