name: PR Checks

on:
  merge_group:
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-build:
    name: Run Tests and Build
    runs-on: nomsterrunner  # Using the specified self-hosted Linux runner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'  # Using the same Go version as in go.mod
          cache: true

      - name: Install Fyne dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libgl1-mesa-dev xorg-dev

      - name: Install MinGW for cross-compilation
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64-x86-64 gcc-mingw-w64

      - name: Install dependencies
        run: go mod download

      - name: Run Tests
        run: go test -v ./...
        
      - name: Build for Windows
        env:
          CGO_ENABLED: 1
          GOOS: windows
          GOARCH: amd64
          CC: x86_64-w64-mingw32-gcc
        run: |
          # Cross-compile for Windows
          go build -o eu-clams.exe ./cmd/app
